### ISSUE TITLE
ERROR: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username

### ISSUE THREAD

**Issue by Cyber5imon** [pepitooo/tidal_backup_favorites#1]
Could there be an issue with usernames that include a plus sign?
```
python3 main.py --backup --user "SPDurkee+Tidal20220110@gmail.com" --password "XXXXXXX"
Namespace(backup=True, filename=None, password='XXXXXX', restore=False, user='SPDurkee+Tidal20220110@gmail.com')
{"status":401,"subStatus":8003,"userMessage":"Client not found"}
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(sys.argv[1:])
  File "main.py", line 80, in main
    session.login(args_parsed.user, args_parsed.password)
  File "/home/simon/.local/lib/python3.8/site-packages/tidalapi/__init__.py", line 198, in login
    request.raise_for_status()
  File "/home/simon/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username
```

**Comment by pepitooo** [comment]
Hello, sorry for that, the tidal api changed, I will have a look if I can update it.
But now instead using a login and pass directly they use an oauth system
